import torch
torch.__version__
a=torch.rand(5,4)
print(a)
torch.manual_seed(42)
a=torch.randn(3,3)
b=torch.randn(3,3)
print(a,'\n', b)
print(torch.add(a,b), '\n')
print(torch.sub(a,b), '\n')
print(torch.mm(a,b), '\n')
print(torch.div(a,b), '\n')
print(a,'\n')
torch.t(a)
a=torch.tensor([[1,2],[3,4]])
b=torch.tensor([[5,6],[7,8]])
print (a,'\n')
print(b)
torch.cat((a,b),dim=1)
